Repository Innovateninjas/Paws-frontend, pull requests merged in 2024-05, with the labels that each got.

#300 Adds new favicon
  favicon (2).ico
Labels: level 1, Gssoc'24

#292 Google auth
  .env.sample
  public/firebase-messaging-sw.js
  public/images/search.png
  public/index.html
  src/firebase.js
  src/pages/user/UserRegistration.jsx
  src/utils/Functions/userAuthService.js
Labels: level 3, Gssoc'24

#328 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: level 2, Gssoc'24

#351 Password must be strong with specific rules #337
  package-lock.json
  package.json
  src/pages/user/UserRegistration.jsx
Labels: level 2, gssoc

#329 Made the stats page of NGO Responsive
  src/pages/ngo/StatPage/LineChart.jsx
  src/pages/ngo/StatPage/StatsMain.jsx
Labels: level 2, gssoc

#359 Adding hover effect over the login now and register now texts
  src/Components/shared/LoginTextLink.jsx
Labels: level 1, gssoc

#357 resolve issue #356
  README.md
Labels: level 2, gssoc

#399 header logo added
  package-lock.json
  public/favicon.ico
  public/index.html
  public/logo.png
  public/logo192.png
  public/logo512.png
Labels: level 1, gssoc

#393 Added scroll bar to all the three pages, i.e. home, register and login pages.
  src/pages/user/HomePage.jsx
  src/pages/user/UserRegistration.jsx
Labels: level 2, gssoc

#386 Added eye toggling functionality for Login/Signup Page (#368)
  src/pages/user/UserRegistration.jsx
Labels: level 3, gssoc

#421 fixed password validations visibility
  src/pages/user/UserRegistration.jsx
Labels: level3, gssoc

#414 ngoProfile page responsive
  src/Components/shared/ProfilePhoto.jsx
  src/pages/ngo/ngoProfile.jsx
Labels: level1, gssoc

#334 #279 contact information page made responsive
  src/pages/user/ReportIncidentPages/ContactInformationPage.jsx
  tailwind.config.js
Labels: level2, gssoc

#411 enhancement of upload profile img
  src/Components/shared/AlertDialog.jsx
  src/Components/shared/ProfilePhoto.jsx
  src/pages/ngo/NgoRegistration/NgoRegister.jsx
  src/pages/user/UserRegistration.jsx
  src/utils/Functions/ngoAuthService.js
  src/utils/Functions/userAuthService.js
Labels: level3, gssoc

#427 Success page made responsive under #272
  package-lock.json
  src/Components/user/FaqComponenet.jsx
  src/pages/user/ReportIncidentPages/SuccessPage.jsx
Labels: level2, gssoc

#415 made login page responsive
  src/pages/user/UserRegistration.jsx
Labels: level2, gssoc

#407 responsive sign up completed
  src/App.css
  src/pages/user/UserRegistration.jsx
Labels: level3, gssoc
